### ISSUE TITLE
When compiling the ssr project, an error is reported, and the client is ok

### ISSUE THREAD

**Issue by lyxverycool** [Chris927/react-roughviz#11]

**Comment by Chris927** [comment]
Hi @lyxverycool Thanks for reporting this.

Please provide an example project or repository that demonstrates the issue.

**Comment by Chris927** [comment]
Hi @lyxverycool 

As I am unable to reproduce the issue with an example, I am closing this issue.

Feel free to re-open, once you can provide an example.
