### ISSUE TITLE
Line chart with object data doesn't work

### ISSUE THREAD

**Issue by haikyuu** [Chris927/react-roughviz#5]
Here is the codesandbox to reproduce the issue: https://codesandbox.io/s/react-codesandbox-wb9ew

I opened a [PR in the roughviz repo](https://github.com/jwilber/roughViz/pull/20) that fixes the problem, but i want to track it here as well since i couldn't reproduce it with the raw library

**Comment by haikyuu** [comment]
here is the stacktrace 
![image](https://user-images.githubusercontent.com/8558836/69341531-c9d5d900-0c7a-11ea-8dcb-6ffb45cd539a.png)

**Comment by Chris927** [comment]
Hey @haikyuu Thanks for this!

I had a quick look.

You can work around the issue by setting `interactive={false}`, as the error arises in `addInteraction()`.

Please note that [your fix](https://github.com/jwilber/roughViz/pull/20) may break other things, as `drawFromFile()` still uses `this.data.map()`. If my rough understanding of the is correct, then in the case of `drawFromFile()` `this.data` is expected to be an array.

**Comment by Chris927** [comment]
Hy @haikyuu your fix has been merged, so I assume this issue can be closed.
