### ISSUE TITLE
duplicate create svg when changing props

### ISSUE THREAD

**Issue by ninpeng** [Chris927/react-roughviz#9]
When changing props two times, create two svg child.

I will solved it.

Fixes #10

**Comment by Chris927** [comment]
Hi @ninpeng I don't see why this is necessary. Can you provide an example to reproduce the issue?

**Comment by ninpeng** [comment]
example : https://codesandbox.io/s/react-codesandbox-dlr54
this exsample used by react-roughviz version 0.17
Click the button twice or third time than create duplicate chart.

**Comment by Chris927** [comment]
Thank you, @ninpeng ! Your way of removing the child nodes works, the previous way not, strangely.

I've merged your changes, and published v0.1.8 with your fix.
